// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connect.sql

package sqlcgen

import (
	"context"
)

const clearConnectDefault = `-- name: ClearConnectDefault :exec
UPDATE connect_connections SET is_default = 0
`

func (q *Queries) ClearConnectDefault(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearConnectDefault)
	return err
}

const countConnectConnections = `-- name: CountConnectConnections :one
SELECT COUNT(*) FROM connect_connections
`

func (q *Queries) CountConnectConnections(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConnectConnections)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteConnectConnection = `-- name: DeleteConnectConnection :execrows
DELETE FROM connect_connections WHERE id = ?1
`

func (q *Queries) DeleteConnectConnection(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteConnectConnection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getConnectConnection = `-- name: GetConnectConnection :one
SELECT id, label, base_url, token, admin_token, kind, is_default, created_at, updated_at FROM connect_connections WHERE id = ?1
`

func (q *Queries) GetConnectConnection(ctx context.Context, id string) (ConnectConnection, error) {
	row := q.db.QueryRowContext(ctx, getConnectConnection, id)
	var i ConnectConnection
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.BaseUrl,
		&i.Token,
		&i.AdminToken,
		&i.Kind,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectConnections = `-- name: ListConnectConnections :many
SELECT id, label, base_url, token, admin_token, kind, is_default, created_at, updated_at FROM connect_connections
ORDER BY is_default DESC, updated_at DESC, id DESC
`

func (q *Queries) ListConnectConnections(ctx context.Context) ([]ConnectConnection, error) {
	rows, err := q.db.QueryContext(ctx, listConnectConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectConnection{}
	for rows.Next() {
		var i ConnectConnection
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.BaseUrl,
			&i.Token,
			&i.AdminToken,
			&i.Kind,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConnectDefault = `-- name: SetConnectDefault :execrows
UPDATE connect_connections SET is_default = 1, updated_at = ?1 WHERE id = ?2
`

type SetConnectDefaultParams struct {
	UpdatedAt int64
	ID        string
}

func (q *Queries) SetConnectDefault(ctx context.Context, arg SetConnectDefaultParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setConnectDefault, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertConnectConnection = `-- name: UpsertConnectConnection :exec
INSERT INTO connect_connections (
    id, label, base_url, token, admin_token, kind, is_default, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9
)
ON CONFLICT(id) DO UPDATE SET
    label = excluded.label,
    base_url = excluded.base_url,
    token = excluded.token,
    admin_token = excluded.admin_token,
    kind = excluded.kind,
    is_default = excluded.is_default,
    updated_at = excluded.updated_at
`

type UpsertConnectConnectionParams struct {
	ID         string
	Label      string
	BaseUrl    string
	Token      string
	AdminToken string
	Kind       string
	IsDefault  int64
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) UpsertConnectConnection(ctx context.Context, arg UpsertConnectConnectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertConnectConnection,
		arg.ID,
		arg.Label,
		arg.BaseUrl,
		arg.Token,
		arg.AdminToken,
		arg.Kind,
		arg.IsDefault,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
