// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contexts.sql

package sqlcgen

import (
	"context"
)

const countContexts = `-- name: CountContexts :one
SELECT COUNT(*) FROM contexts
WHERE (?1 = '' OR title LIKE '%' || ?1 || '%')
`

func (q *Queries) CountContexts(ctx context.Context, search interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContexts, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteContext = `-- name: DeleteContext :execrows
DELETE FROM contexts WHERE id = ?1
`

func (q *Queries) DeleteContext(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteContext, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getContext = `-- name: GetContext :one
SELECT id, title, context, header, updated_by_type, updated_by_address, created_at, updated_at FROM contexts WHERE id = ?1
`

func (q *Queries) GetContext(ctx context.Context, id string) (Context, error) {
	row := q.db.QueryRowContext(ctx, getContext, id)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Context,
		&i.Header,
		&i.UpdatedByType,
		&i.UpdatedByAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContexts = `-- name: ListContexts :many
SELECT id, title, context, header, updated_by_type, updated_by_address, created_at, updated_at FROM contexts
WHERE (?1 = '' OR title LIKE '%' || ?1 || '%')
ORDER BY updated_at DESC, id DESC
LIMIT ?3 OFFSET ?2
`

type ListContextsParams struct {
	Search interface{}
	Offset int64
	Limit  int64
}

func (q *Queries) ListContexts(ctx context.Context, arg ListContextsParams) ([]Context, error) {
	rows, err := q.db.QueryContext(ctx, listContexts, arg.Search, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Context{}
	for rows.Next() {
		var i Context
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Context,
			&i.Header,
			&i.UpdatedByType,
			&i.UpdatedByAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContext = `-- name: UpsertContext :exec
INSERT INTO contexts (
    id, title, context, header, updated_by_type, updated_by_address, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8
)
ON CONFLICT(id) DO UPDATE SET
    title = excluded.title,
    context = excluded.context,
    header = excluded.header,
    updated_by_type = excluded.updated_by_type,
    updated_by_address = excluded.updated_by_address,
    updated_at = excluded.updated_at
`

type UpsertContextParams struct {
	ID               string
	Title            string
	Context          string
	Header           string
	UpdatedByType    string
	UpdatedByAddress string
	CreatedAt        int64
	UpdatedAt        int64
}

func (q *Queries) UpsertContext(ctx context.Context, arg UpsertContextParams) error {
	_, err := q.db.ExecContext(ctx, upsertContext,
		arg.ID,
		arg.Title,
		arg.Context,
		arg.Header,
		arg.UpdatedByType,
		arg.UpdatedByAddress,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
