// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: extensions.sql

package sqlcgen

import (
	"context"
)

const countExtensions = `-- name: CountExtensions :one
SELECT COUNT(*) FROM extensions
WHERE (?1 = '' OR name LIKE '%' || ?1 || '%')
  AND (?2 = '' OR kind = ?2)
`

type CountExtensionsParams struct {
	Search interface{}
	Kind   interface{}
}

func (q *Queries) CountExtensions(ctx context.Context, arg CountExtensionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExtensions, arg.Search, arg.Kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExtension = `-- name: DeleteExtension :execrows
DELETE FROM extensions WHERE id = ?1
`

func (q *Queries) DeleteExtension(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExtension, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePluginActions = `-- name: DeletePluginActions :execrows
DELETE FROM extensions WHERE plugin_id = ?1 AND action <> ''
`

// Drop every palette row derived from one plugin's @actions, leaving the
// plugin's own registration row (action = ”) alone. The sync pass replaces
// rather than merges, so a method the plugin dropped disappears with it.
func (q *Queries) DeletePluginActions(ctx context.Context, pluginID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePluginActions, pluginID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBuiltinByName = `-- name: GetBuiltinByName :one
SELECT id, kind, type, name, description, plugin_id, icon, params, bind_to, install, "action", parent_id, created_at, updated_at FROM extensions WHERE kind = 'builtin' AND name = ?1
`

func (q *Queries) GetBuiltinByName(ctx context.Context, name string) (Extension, error) {
	row := q.db.QueryRowContext(ctx, getBuiltinByName, name)
	var i Extension
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.PluginID,
		&i.Icon,
		&i.Params,
		&i.BindTo,
		&i.Install,
		&i.Action,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExtension = `-- name: GetExtension :one
SELECT id, kind, type, name, description, plugin_id, icon, params, bind_to, install, "action", parent_id, created_at, updated_at FROM extensions WHERE id = ?1
`

func (q *Queries) GetExtension(ctx context.Context, id string) (Extension, error) {
	row := q.db.QueryRowContext(ctx, getExtension, id)
	var i Extension
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.PluginID,
		&i.Icon,
		&i.Params,
		&i.BindTo,
		&i.Install,
		&i.Action,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExtensions = `-- name: ListExtensions :many
SELECT id, kind, type, name, description, plugin_id, icon, params, bind_to, install, "action", parent_id, created_at, updated_at FROM extensions
WHERE (?1 = '' OR name LIKE '%' || ?1 || '%')
  AND (?2 = '' OR kind = ?2)
ORDER BY updated_at DESC, id DESC
LIMIT ?4 OFFSET ?3
`

type ListExtensionsParams struct {
	Search interface{}
	Kind   interface{}
	Offset int64
	Limit  int64
}

func (q *Queries) ListExtensions(ctx context.Context, arg ListExtensionsParams) ([]Extension, error) {
	rows, err := q.db.QueryContext(ctx, listExtensions,
		arg.Search,
		arg.Kind,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Extension{}
	for rows.Next() {
		var i Extension
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.PluginID,
			&i.Icon,
			&i.Params,
			&i.BindTo,
			&i.Install,
			&i.Action,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExtension = `-- name: UpsertExtension :exec
INSERT INTO extensions (
    id, kind, type, name, description, plugin_id, icon, params, bind_to, install, action, parent_id, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14
)
ON CONFLICT(id) DO UPDATE SET
    kind = excluded.kind,
    type = excluded.type,
    name = excluded.name,
    description = excluded.description,
    plugin_id = excluded.plugin_id,
    icon = excluded.icon,
    params = excluded.params,
    bind_to = excluded.bind_to,
    install = excluded.install,
    action = excluded.action,
    parent_id = excluded.parent_id,
    updated_at = excluded.updated_at
`

type UpsertExtensionParams struct {
	ID          string
	Kind        string
	Type        string
	Name        string
	Description string
	PluginID    string
	Icon        string
	Params      string
	BindTo      string
	Install     string
	Action      string
	ParentID    string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) UpsertExtension(ctx context.Context, arg UpsertExtensionParams) error {
	_, err := q.db.ExecContext(ctx, upsertExtension,
		arg.ID,
		arg.Kind,
		arg.Type,
		arg.Name,
		arg.Description,
		arg.PluginID,
		arg.Icon,
		arg.Params,
		arg.BindTo,
		arg.Install,
		arg.Action,
		arg.ParentID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
