// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: human_tasks.sql

package sqlcgen

import (
	"context"
)

const countHumanTasks = `-- name: CountHumanTasks :one
SELECT COUNT(*) FROM human_tasks
WHERE (?1 = '' OR title LIKE '%' || ?1 || '%')
  AND (?2 = '' OR status = ?2)
  AND (?3 = '' OR flow_id = ?3)
`

type CountHumanTasksParams struct {
	Search interface{}
	Status interface{}
	FlowID interface{}
}

func (q *Queries) CountHumanTasks(ctx context.Context, arg CountHumanTasksParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHumanTasks, arg.Search, arg.Status, arg.FlowID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteHumanTask = `-- name: DeleteHumanTask :execrows
DELETE FROM human_tasks WHERE id = ?1
`

func (q *Queries) DeleteHumanTask(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHumanTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getHumanTask = `-- name: GetHumanTask :one
SELECT id, title, status, pid, flow_id, node_id, context_id, mode, channel, prompt, settings_id, node_key, instance_id, questions, messages, data, nexts, created_at, updated_at, closed_at FROM human_tasks WHERE id = ?1
`

func (q *Queries) GetHumanTask(ctx context.Context, id string) (HumanTask, error) {
	row := q.db.QueryRowContext(ctx, getHumanTask, id)
	var i HumanTask
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Pid,
		&i.FlowID,
		&i.NodeID,
		&i.ContextID,
		&i.Mode,
		&i.Channel,
		&i.Prompt,
		&i.SettingsID,
		&i.NodeKey,
		&i.InstanceID,
		&i.Questions,
		&i.Messages,
		&i.Data,
		&i.Nexts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const listHumanTasks = `-- name: ListHumanTasks :many
SELECT id, title, status, pid, flow_id, node_id, context_id, mode, channel, prompt, settings_id, node_key, instance_id, questions, messages, data, nexts, created_at, updated_at, closed_at FROM human_tasks
WHERE (?1 = '' OR title LIKE '%' || ?1 || '%')
  AND (?2 = '' OR status = ?2)
  AND (?3 = '' OR flow_id = ?3)
ORDER BY updated_at DESC, id DESC
LIMIT ?5 OFFSET ?4
`

type ListHumanTasksParams struct {
	Search interface{}
	Status interface{}
	FlowID interface{}
	Offset int64
	Limit  int64
}

func (q *Queries) ListHumanTasks(ctx context.Context, arg ListHumanTasksParams) ([]HumanTask, error) {
	rows, err := q.db.QueryContext(ctx, listHumanTasks,
		arg.Search,
		arg.Status,
		arg.FlowID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HumanTask{}
	for rows.Next() {
		var i HumanTask
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Pid,
			&i.FlowID,
			&i.NodeID,
			&i.ContextID,
			&i.Mode,
			&i.Channel,
			&i.Prompt,
			&i.SettingsID,
			&i.NodeKey,
			&i.InstanceID,
			&i.Questions,
			&i.Messages,
			&i.Data,
			&i.Nexts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHumanTask = `-- name: UpsertHumanTask :exec
INSERT INTO human_tasks (
    id, title, status, pid, instance_id, flow_id, node_id, context_id,
    mode, channel, prompt, settings_id, node_key,
    questions, messages, data, nexts, created_at, updated_at, closed_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8,
    ?9, ?10, ?11, ?12, ?13,
    ?14, ?15, ?16, ?17, ?18, ?19, ?20
)
ON CONFLICT(id) DO UPDATE SET
    title = excluded.title,
    status = excluded.status,
    pid = excluded.pid,
    instance_id = excluded.instance_id,
    flow_id = excluded.flow_id,
    node_id = excluded.node_id,
    context_id = excluded.context_id,
    mode = excluded.mode,
    channel = excluded.channel,
    prompt = excluded.prompt,
    settings_id = excluded.settings_id,
    node_key = excluded.node_key,
    questions = excluded.questions,
    messages = excluded.messages,
    data = excluded.data,
    nexts = excluded.nexts,
    updated_at = excluded.updated_at,
    closed_at = excluded.closed_at
`

type UpsertHumanTaskParams struct {
	ID         string
	Title      string
	Status     string
	Pid        string
	InstanceID string
	FlowID     string
	NodeID     string
	ContextID  string
	Mode       string
	Channel    string
	Prompt     string
	SettingsID string
	NodeKey    string
	Questions  string
	Messages   string
	Data       string
	Nexts      string
	CreatedAt  int64
	UpdatedAt  int64
	ClosedAt   int64
}

func (q *Queries) UpsertHumanTask(ctx context.Context, arg UpsertHumanTaskParams) error {
	_, err := q.db.ExecContext(ctx, upsertHumanTask,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.Pid,
		arg.InstanceID,
		arg.FlowID,
		arg.NodeID,
		arg.ContextID,
		arg.Mode,
		arg.Channel,
		arg.Prompt,
		arg.SettingsID,
		arg.NodeKey,
		arg.Questions,
		arg.Messages,
		arg.Data,
		arg.Nexts,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ClosedAt,
	)
	return err
}
