// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memory.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createMemoryStore = `-- name: CreateMemoryStore :exec
INSERT INTO memory_stores (
    id, name, type, description, vector_config, document_config, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8
)
`

type CreateMemoryStoreParams struct {
	ID             string
	Name           string
	Type           string
	Description    string
	VectorConfig   sql.NullString
	DocumentConfig sql.NullString
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) CreateMemoryStore(ctx context.Context, arg CreateMemoryStoreParams) error {
	_, err := q.db.ExecContext(ctx, createMemoryStore,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.VectorConfig,
		arg.DocumentConfig,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteMemoryStore = `-- name: DeleteMemoryStore :execrows
DELETE FROM memory_stores WHERE id = ?1
`

func (q *Queries) DeleteMemoryStore(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMemoryStore, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMemoryStore = `-- name: GetMemoryStore :one
SELECT id, name, type, description, vector_config, document_config, created_at, updated_at FROM memory_stores WHERE id = ?1
`

func (q *Queries) GetMemoryStore(ctx context.Context, id string) (MemoryStore, error) {
	row := q.db.QueryRowContext(ctx, getMemoryStore, id)
	var i MemoryStore
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.VectorConfig,
		&i.DocumentConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMemoryStores = `-- name: ListMemoryStores :many
SELECT id, name, type, description, vector_config, document_config, created_at, updated_at FROM memory_stores
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListMemoryStores(ctx context.Context) ([]MemoryStore, error) {
	rows, err := q.db.QueryContext(ctx, listMemoryStores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryStore{}
	for rows.Next() {
		var i MemoryStore
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.VectorConfig,
			&i.DocumentConfig,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
