// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Context struct {
	ID               string
	Title            string
	Context          string
	Header           string
	UpdatedByType    string
	UpdatedByAddress string
	CreatedAt        int64
	UpdatedAt        int64
}

type HumanTask struct {
	ID        string
	Title     string
	Status    string
	Pid       string
	FlowID    string
	NodeID    string
	ContextID string
	Questions string
	Messages  string
	Data      string
	CreatedAt int64
	UpdatedAt int64
	ClosedAt  int64
}

type MemoryStore struct {
	ID             string
	Name           string
	Type           string
	Description    string
	VectorConfig   sql.NullString
	DocumentConfig sql.NullString
	CreatedAt      int64
	UpdatedAt      int64
}

type Prompt struct {
	ID          string
	Title       string
	Description string
	Template    string
	Variables   string
	Tags        string
	CreatedAt   int64
	UpdatedAt   int64
}

type Workflow struct {
	ID        string
	Title     string
	ViewFlow  string
	CreatedAt int64
	UpdatedAt int64
}
