// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Context struct {
	ID               string
	Title            string
	Context          string
	Header           string
	UpdatedByType    string
	UpdatedByAddress string
	CreatedAt        int64
	UpdatedAt        int64
}

type Extension struct {
	ID          string
	Kind        string
	Type        string
	Name        string
	Description string
	PluginID    string
	Icon        string
	Params      string
	BindTo      string
	Install     string
	Action      string
	ParentID    string
	CreatedAt   int64
	UpdatedAt   int64
}

type HumanTask struct {
	ID        string
	Title     string
	Status    string
	Pid       string
	FlowID    string
	NodeID    string
	ContextID string
	Mode      string
	Channel   string
	Prompt    string
	Questions string
	Messages  string
	Data      string
	Nexts     string
	CreatedAt int64
	UpdatedAt int64
	ClosedAt  int64
}

type MemoryStore struct {
	ID             string
	Name           string
	Type           string
	Description    string
	VectorConfig   sql.NullString
	DocumentConfig sql.NullString
	CreatedAt      int64
	UpdatedAt      int64
}

type NodeSetting struct {
	ID         string
	NodeUniqID string
	NodeType   string
	Title      string
	Settings   string
	CreatedAt  int64
	UpdatedAt  int64
}

type Process struct {
	IndexID     int64
	Pid         string
	FlowID      string
	ContextID   string
	StartNodeID string
	Status      string
	ResourceUrl string
	Request     string
	Meta        string
	Error       string
	ScheduledAt int64
	StartedAt   int64
	FinishedAt  int64
	DurationMs  int64
	CreatedAt   int64
	UpdatedAt   int64
}

type Prompt struct {
	ID          string
	Title       string
	Description string
	Template    string
	Variables   string
	Tags        string
	CreatedAt   int64
	UpdatedAt   int64
}

type Workflow struct {
	ID        string
	Title     string
	ViewFlow  string
	CreatedAt int64
	UpdatedAt int64
}
