// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node_settings.sql

package sqlcgen

import (
	"context"
)

const countNodeSettings = `-- name: CountNodeSettings :one
SELECT COUNT(*) FROM node_settings
WHERE (?1 = '' OR title LIKE '%' || ?1 || '%')
  AND (?2 = '' OR node_uniq_id = ?2)
`

type CountNodeSettingsParams struct {
	Search     interface{}
	NodeUniqID interface{}
}

func (q *Queries) CountNodeSettings(ctx context.Context, arg CountNodeSettingsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNodeSettings, arg.Search, arg.NodeUniqID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteNodeSetting = `-- name: DeleteNodeSetting :execrows
DELETE FROM node_settings WHERE id = ?1
`

func (q *Queries) DeleteNodeSetting(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNodeSetting, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNodeSetting = `-- name: GetNodeSetting :one
SELECT id, node_uniq_id, node_type, title, settings, created_at, updated_at FROM node_settings WHERE id = ?1
`

func (q *Queries) GetNodeSetting(ctx context.Context, id string) (NodeSetting, error) {
	row := q.db.QueryRowContext(ctx, getNodeSetting, id)
	var i NodeSetting
	err := row.Scan(
		&i.ID,
		&i.NodeUniqID,
		&i.NodeType,
		&i.Title,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNodeSettings = `-- name: ListNodeSettings :many
SELECT id, node_uniq_id, node_type, title, settings, created_at, updated_at FROM node_settings
WHERE (?1 = '' OR title LIKE '%' || ?1 || '%')
  AND (?2 = '' OR node_uniq_id = ?2)
ORDER BY updated_at DESC, id DESC
LIMIT ?4 OFFSET ?3
`

type ListNodeSettingsParams struct {
	Search     interface{}
	NodeUniqID interface{}
	Offset     int64
	Limit      int64
}

func (q *Queries) ListNodeSettings(ctx context.Context, arg ListNodeSettingsParams) ([]NodeSetting, error) {
	rows, err := q.db.QueryContext(ctx, listNodeSettings,
		arg.Search,
		arg.NodeUniqID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeSetting{}
	for rows.Next() {
		var i NodeSetting
		if err := rows.Scan(
			&i.ID,
			&i.NodeUniqID,
			&i.NodeType,
			&i.Title,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNodeSetting = `-- name: UpsertNodeSetting :exec
INSERT INTO node_settings (
    id, node_uniq_id, node_type, title, settings, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7
)
ON CONFLICT(id) DO UPDATE SET
    node_uniq_id = excluded.node_uniq_id,
    node_type = excluded.node_type,
    title = excluded.title,
    settings = excluded.settings,
    updated_at = excluded.updated_at
`

type UpsertNodeSettingParams struct {
	ID         string
	NodeUniqID string
	NodeType   string
	Title      string
	Settings   string
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) UpsertNodeSetting(ctx context.Context, arg UpsertNodeSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertNodeSetting,
		arg.ID,
		arg.NodeUniqID,
		arg.NodeType,
		arg.Title,
		arg.Settings,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
