// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: processes.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countProcesses = `-- name: CountProcesses :one
SELECT COUNT(*) FROM processes
WHERE (?1 = '' OR pid LIKE '%' || ?1 || '%' OR flow_id LIKE '%' || ?1 || '%')
  AND (?2 = '' OR status = ?2)
  AND (?3 = '' OR pid = ?3)
  AND (?4 = '' OR flow_id = ?4)
  AND (?5 = '' OR instance_id = ?5)
`

type CountProcessesParams struct {
	Search     interface{}
	Status     interface{}
	Pid        interface{}
	FlowID     interface{}
	InstanceID interface{}
}

func (q *Queries) CountProcesses(ctx context.Context, arg CountProcessesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProcesses,
		arg.Search,
		arg.Status,
		arg.Pid,
		arg.FlowID,
		arg.InstanceID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProcess = `-- name: DeleteProcess :execrows
DELETE FROM processes WHERE index_id = ?1
`

func (q *Queries) DeleteProcess(ctx context.Context, indexID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProcess, indexID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNextScheduledProcess = `-- name: GetNextScheduledProcess :one
SELECT index_id, pid, instance_id, flow_id, context_id, start_node_id, status, resource_url, request, meta, snapshot, error, scheduled_at, started_at, finished_at, duration_ms, created_at, updated_at FROM processes
WHERE status = 'scheduled'
ORDER BY scheduled_at ASC, index_id ASC
LIMIT 1
`

func (q *Queries) GetNextScheduledProcess(ctx context.Context) (Process, error) {
	row := q.db.QueryRowContext(ctx, getNextScheduledProcess)
	var i Process
	err := row.Scan(
		&i.IndexID,
		&i.Pid,
		&i.InstanceID,
		&i.FlowID,
		&i.ContextID,
		&i.StartNodeID,
		&i.Status,
		&i.ResourceUrl,
		&i.Request,
		&i.Meta,
		&i.Snapshot,
		&i.Error,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProcess = `-- name: GetProcess :one
SELECT index_id, pid, instance_id, flow_id, context_id, start_node_id, status, resource_url, request, meta, snapshot, error, scheduled_at, started_at, finished_at, duration_ms, created_at, updated_at FROM processes WHERE index_id = ?1
`

func (q *Queries) GetProcess(ctx context.Context, indexID int64) (Process, error) {
	row := q.db.QueryRowContext(ctx, getProcess, indexID)
	var i Process
	err := row.Scan(
		&i.IndexID,
		&i.Pid,
		&i.InstanceID,
		&i.FlowID,
		&i.ContextID,
		&i.StartNodeID,
		&i.Status,
		&i.ResourceUrl,
		&i.Request,
		&i.Meta,
		&i.Snapshot,
		&i.Error,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunningProcessByPID = `-- name: GetRunningProcessByPID :one
SELECT index_id, pid, instance_id, flow_id, context_id, start_node_id, status, resource_url, request, meta, snapshot, error, scheduled_at, started_at, finished_at, duration_ms, created_at, updated_at FROM processes
WHERE pid = ?1 AND status = 'running'
ORDER BY index_id DESC
LIMIT 1
`

func (q *Queries) GetRunningProcessByPID(ctx context.Context, pid string) (Process, error) {
	row := q.db.QueryRowContext(ctx, getRunningProcessByPID, pid)
	var i Process
	err := row.Scan(
		&i.IndexID,
		&i.Pid,
		&i.InstanceID,
		&i.FlowID,
		&i.ContextID,
		&i.StartNodeID,
		&i.Status,
		&i.ResourceUrl,
		&i.Request,
		&i.Meta,
		&i.Snapshot,
		&i.Error,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProcess = `-- name: InsertProcess :execresult
INSERT INTO processes (
    pid, instance_id, flow_id, context_id, start_node_id, status, resource_url,
    request, meta, snapshot, error, scheduled_at, started_at, finished_at, duration_ms,
    created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7,
    ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15,
    ?16, ?17
)
`

type InsertProcessParams struct {
	Pid         string
	InstanceID  string
	FlowID      string
	ContextID   string
	StartNodeID string
	Status      string
	ResourceUrl string
	Request     string
	Meta        string
	Snapshot    string
	Error       string
	ScheduledAt int64
	StartedAt   int64
	FinishedAt  int64
	DurationMs  int64
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) InsertProcess(ctx context.Context, arg InsertProcessParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertProcess,
		arg.Pid,
		arg.InstanceID,
		arg.FlowID,
		arg.ContextID,
		arg.StartNodeID,
		arg.Status,
		arg.ResourceUrl,
		arg.Request,
		arg.Meta,
		arg.Snapshot,
		arg.Error,
		arg.ScheduledAt,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const listDueScheduledProcesses = `-- name: ListDueScheduledProcesses :many
SELECT index_id, pid, instance_id, flow_id, context_id, start_node_id, status, resource_url, request, meta, snapshot, error, scheduled_at, started_at, finished_at, duration_ms, created_at, updated_at FROM processes
WHERE status = 'scheduled' AND scheduled_at <= ?1
ORDER BY scheduled_at ASC, index_id ASC
`

func (q *Queries) ListDueScheduledProcesses(ctx context.Context, now int64) ([]Process, error) {
	rows, err := q.db.QueryContext(ctx, listDueScheduledProcesses, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Process{}
	for rows.Next() {
		var i Process
		if err := rows.Scan(
			&i.IndexID,
			&i.Pid,
			&i.InstanceID,
			&i.FlowID,
			&i.ContextID,
			&i.StartNodeID,
			&i.Status,
			&i.ResourceUrl,
			&i.Request,
			&i.Meta,
			&i.Snapshot,
			&i.Error,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcesses = `-- name: ListProcesses :many
SELECT index_id, pid, instance_id, flow_id, context_id, start_node_id, status, resource_url, request, meta, snapshot, error, scheduled_at, started_at, finished_at, duration_ms, created_at, updated_at FROM processes
WHERE (?1 = '' OR pid LIKE '%' || ?1 || '%' OR flow_id LIKE '%' || ?1 || '%')
  AND (?2 = '' OR status = ?2)
  AND (?3 = '' OR pid = ?3)
  AND (?4 = '' OR flow_id = ?4)
  AND (?5 = '' OR instance_id = ?5)
ORDER BY updated_at DESC, index_id DESC
LIMIT ?7 OFFSET ?6
`

type ListProcessesParams struct {
	Search     interface{}
	Status     interface{}
	Pid        interface{}
	FlowID     interface{}
	InstanceID interface{}
	Offset     int64
	Limit      int64
}

func (q *Queries) ListProcesses(ctx context.Context, arg ListProcessesParams) ([]Process, error) {
	rows, err := q.db.QueryContext(ctx, listProcesses,
		arg.Search,
		arg.Status,
		arg.Pid,
		arg.FlowID,
		arg.InstanceID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Process{}
	for rows.Next() {
		var i Process
		if err := rows.Scan(
			&i.IndexID,
			&i.Pid,
			&i.InstanceID,
			&i.FlowID,
			&i.ContextID,
			&i.StartNodeID,
			&i.Status,
			&i.ResourceUrl,
			&i.Request,
			&i.Meta,
			&i.Snapshot,
			&i.Error,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProcess = `-- name: UpdateProcess :execrows
UPDATE processes SET
    pid = ?1,
    instance_id = ?2,
    flow_id = ?3,
    context_id = ?4,
    start_node_id = ?5,
    status = ?6,
    resource_url = ?7,
    request = ?8,
    meta = ?9,
    snapshot = ?10,
    error = ?11,
    scheduled_at = ?12,
    started_at = ?13,
    finished_at = ?14,
    duration_ms = ?15,
    updated_at = ?16
WHERE index_id = ?17
`

type UpdateProcessParams struct {
	Pid         string
	InstanceID  string
	FlowID      string
	ContextID   string
	StartNodeID string
	Status      string
	ResourceUrl string
	Request     string
	Meta        string
	Snapshot    string
	Error       string
	ScheduledAt int64
	StartedAt   int64
	FinishedAt  int64
	DurationMs  int64
	UpdatedAt   int64
	IndexID     int64
}

func (q *Queries) UpdateProcess(ctx context.Context, arg UpdateProcessParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProcess,
		arg.Pid,
		arg.InstanceID,
		arg.FlowID,
		arg.ContextID,
		arg.StartNodeID,
		arg.Status,
		arg.ResourceUrl,
		arg.Request,
		arg.Meta,
		arg.Snapshot,
		arg.Error,
		arg.ScheduledAt,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
		arg.UpdatedAt,
		arg.IndexID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
