// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prompts.sql

package sqlcgen

import (
	"context"
)

const countPrompts = `-- name: CountPrompts :one
SELECT COUNT(*) FROM prompts
WHERE (?1 = '' OR title LIKE '%' || ?1 || '%' OR description LIKE '%' || ?1 || '%')
`

func (q *Queries) CountPrompts(ctx context.Context, search interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrompts, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePrompt = `-- name: DeletePrompt :execrows
DELETE FROM prompts WHERE id = ?1
`

func (q *Queries) DeletePrompt(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePrompt, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPrompt = `-- name: GetPrompt :one
SELECT id, title, description, template, variables, tags, created_at, updated_at FROM prompts WHERE id = ?1
`

func (q *Queries) GetPrompt(ctx context.Context, id string) (Prompt, error) {
	row := q.db.QueryRowContext(ctx, getPrompt, id)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Template,
		&i.Variables,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPrompts = `-- name: ListPrompts :many
SELECT id, title, description, template, variables, tags, created_at, updated_at FROM prompts
WHERE (?1 = '' OR title LIKE '%' || ?1 || '%' OR description LIKE '%' || ?1 || '%')
ORDER BY updated_at DESC, id DESC
LIMIT ?3 OFFSET ?2
`

type ListPromptsParams struct {
	Search interface{}
	Offset int64
	Limit  int64
}

func (q *Queries) ListPrompts(ctx context.Context, arg ListPromptsParams) ([]Prompt, error) {
	rows, err := q.db.QueryContext(ctx, listPrompts, arg.Search, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prompt{}
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Template,
			&i.Variables,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPrompt = `-- name: UpsertPrompt :exec
INSERT INTO prompts (
    id, title, description, template, variables, tags, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8
)
ON CONFLICT(id) DO UPDATE SET
    title = excluded.title,
    description = excluded.description,
    template = excluded.template,
    variables = excluded.variables,
    tags = excluded.tags,
    updated_at = excluded.updated_at
`

type UpsertPromptParams struct {
	ID          string
	Title       string
	Description string
	Template    string
	Variables   string
	Tags        string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) UpsertPrompt(ctx context.Context, arg UpsertPromptParams) error {
	_, err := q.db.ExecContext(ctx, upsertPrompt,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Template,
		arg.Variables,
		arg.Tags,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
