// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CountContexts(ctx context.Context, search interface{}) (int64, error)
	CountPrompts(ctx context.Context, search interface{}) (int64, error)
	CountWorkflows(ctx context.Context, search interface{}) (int64, error)
	CreateMemoryStore(ctx context.Context, arg CreateMemoryStoreParams) error
	DeleteContext(ctx context.Context, id string) (int64, error)
	DeleteMemoryStore(ctx context.Context, id string) (int64, error)
	DeletePrompt(ctx context.Context, id string) (int64, error)
	DeleteWorkflow(ctx context.Context, id string) (int64, error)
	GetContext(ctx context.Context, id string) (Context, error)
	GetMemoryStore(ctx context.Context, id string) (MemoryStore, error)
	GetPrompt(ctx context.Context, id string) (Prompt, error)
	GetWorkflow(ctx context.Context, id string) (Workflow, error)
	ListContexts(ctx context.Context, arg ListContextsParams) ([]Context, error)
	ListMemoryStores(ctx context.Context) ([]MemoryStore, error)
	ListPrompts(ctx context.Context, arg ListPromptsParams) ([]Prompt, error)
	ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]Workflow, error)
	UpsertContext(ctx context.Context, arg UpsertContextParams) error
	UpsertPrompt(ctx context.Context, arg UpsertPromptParams) error
	UpsertWorkflow(ctx context.Context, arg UpsertWorkflowParams) error
}

var _ Querier = (*Queries)(nil)
