// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram_recipients.sql

package sqlcgen

import (
	"context"
)

const deleteTelegramRecipient = `-- name: DeleteTelegramRecipient :execrows
DELETE FROM telegram_recipients WHERE id = ?1
`

func (q *Queries) DeleteTelegramRecipient(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTelegramRecipient, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listTelegramRecipients = `-- name: ListTelegramRecipients :many
SELECT id, connection, alias, chat_id, type, title, username, first_name, last_name, last_seen_at, created_at, updated_at FROM telegram_recipients
WHERE connection = ?1 AND alias = ?2
ORDER BY last_seen_at DESC, id DESC
LIMIT ?3
`

type ListTelegramRecipientsParams struct {
	Connection string
	Alias      string
	Limit      int64
}

func (q *Queries) ListTelegramRecipients(ctx context.Context, arg ListTelegramRecipientsParams) ([]TelegramRecipient, error) {
	rows, err := q.db.QueryContext(ctx, listTelegramRecipients, arg.Connection, arg.Alias, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TelegramRecipient{}
	for rows.Next() {
		var i TelegramRecipient
		if err := rows.Scan(
			&i.ID,
			&i.Connection,
			&i.Alias,
			&i.ChatID,
			&i.Type,
			&i.Title,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTelegramRecipient = `-- name: UpsertTelegramRecipient :exec
INSERT INTO telegram_recipients (
    id, connection, alias, chat_id, type, title, username, first_name, last_name,
    last_seen_at, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9,
    ?10, ?11, ?12
)
ON CONFLICT(id) DO UPDATE SET
    type = excluded.type,
    title = excluded.title,
    username = excluded.username,
    first_name = excluded.first_name,
    last_name = excluded.last_name,
    -- A chat re-seen out of order must not walk the timestamp backwards.
    last_seen_at = MAX(telegram_recipients.last_seen_at, excluded.last_seen_at),
    updated_at = excluded.updated_at
`

type UpsertTelegramRecipientParams struct {
	ID         string
	Connection string
	Alias      string
	ChatID     string
	Type       string
	Title      string
	Username   string
	FirstName  string
	LastName   string
	LastSeenAt int64
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) UpsertTelegramRecipient(ctx context.Context, arg UpsertTelegramRecipientParams) error {
	_, err := q.db.ExecContext(ctx, upsertTelegramRecipient,
		arg.ID,
		arg.Connection,
		arg.Alias,
		arg.ChatID,
		arg.Type,
		arg.Title,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.LastSeenAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
