// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: triggers.sql

package sqlcgen

import (
	"context"
)

const countTriggers = `-- name: CountTriggers :one
SELECT COUNT(*) FROM triggers
WHERE (?1 = '' OR flow_id = ?1)
  AND (?2 = '' OR kind = ?2)
  AND (?3 = '' OR title LIKE '%' || ?3 || '%')
`

type CountTriggersParams struct {
	FlowID interface{}
	Kind   interface{}
	Search interface{}
}

func (q *Queries) CountTriggers(ctx context.Context, arg CountTriggersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTriggers, arg.FlowID, arg.Kind, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTrigger = `-- name: DeleteTrigger :execrows
DELETE FROM triggers WHERE id = ?1
`

func (q *Queries) DeleteTrigger(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTrigger, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTrigger = `-- name: GetTrigger :one
SELECT id, kind, flow_id, start_node_id, title, enabled, slug, config, cron_effective, last_at, hits, created_at, updated_at FROM triggers WHERE id = ?1
`

func (q *Queries) GetTrigger(ctx context.Context, id string) (Trigger, error) {
	row := q.db.QueryRowContext(ctx, getTrigger, id)
	var i Trigger
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.FlowID,
		&i.StartNodeID,
		&i.Title,
		&i.Enabled,
		&i.Slug,
		&i.Config,
		&i.CronEffective,
		&i.LastAt,
		&i.Hits,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTriggerBySlug = `-- name: GetTriggerBySlug :one
SELECT id, kind, flow_id, start_node_id, title, enabled, slug, config, cron_effective, last_at, hits, created_at, updated_at FROM triggers WHERE slug = ?1 AND enabled = 1
`

func (q *Queries) GetTriggerBySlug(ctx context.Context, slug string) (Trigger, error) {
	row := q.db.QueryRowContext(ctx, getTriggerBySlug, slug)
	var i Trigger
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.FlowID,
		&i.StartNodeID,
		&i.Title,
		&i.Enabled,
		&i.Slug,
		&i.Config,
		&i.CronEffective,
		&i.LastAt,
		&i.Hits,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledSchedules = `-- name: ListEnabledSchedules :many
SELECT id, kind, flow_id, start_node_id, title, enabled, slug, config, cron_effective, last_at, hits, created_at, updated_at FROM triggers WHERE kind = 'schedule' AND enabled = 1 ORDER BY id
`

func (q *Queries) ListEnabledSchedules(ctx context.Context) ([]Trigger, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trigger{}
	for rows.Next() {
		var i Trigger
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.FlowID,
			&i.StartNodeID,
			&i.Title,
			&i.Enabled,
			&i.Slug,
			&i.Config,
			&i.CronEffective,
			&i.LastAt,
			&i.Hits,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTriggers = `-- name: ListTriggers :many
SELECT id, kind, flow_id, start_node_id, title, enabled, slug, config, cron_effective, last_at, hits, created_at, updated_at FROM triggers
WHERE (?1 = '' OR flow_id = ?1)
  AND (?2 = '' OR kind = ?2)
  AND (?3 = '' OR title LIKE '%' || ?3 || '%')
ORDER BY updated_at DESC, id DESC
LIMIT ?5 OFFSET ?4
`

type ListTriggersParams struct {
	FlowID interface{}
	Kind   interface{}
	Search interface{}
	Offset int64
	Limit  int64
}

func (q *Queries) ListTriggers(ctx context.Context, arg ListTriggersParams) ([]Trigger, error) {
	rows, err := q.db.QueryContext(ctx, listTriggers,
		arg.FlowID,
		arg.Kind,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trigger{}
	for rows.Next() {
		var i Trigger
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.FlowID,
			&i.StartNodeID,
			&i.Title,
			&i.Enabled,
			&i.Slug,
			&i.Config,
			&i.CronEffective,
			&i.LastAt,
			&i.Hits,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTriggerState = `-- name: UpdateTriggerState :exec
UPDATE triggers SET last_at = ?1, hits = ?2, updated_at = ?3
WHERE id = ?4
`

type UpdateTriggerStateParams struct {
	LastAt    int64
	Hits      string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateTriggerState(ctx context.Context, arg UpdateTriggerStateParams) error {
	_, err := q.db.ExecContext(ctx, updateTriggerState,
		arg.LastAt,
		arg.Hits,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertTrigger = `-- name: UpsertTrigger :exec
INSERT INTO triggers (
    id, kind, flow_id, start_node_id, title, enabled, slug, config,
    cron_effective, last_at, hits, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8,
    ?9, ?10, ?11, ?12, ?13
)
ON CONFLICT(id) DO UPDATE SET
    kind = excluded.kind,
    flow_id = excluded.flow_id,
    start_node_id = excluded.start_node_id,
    title = excluded.title,
    enabled = excluded.enabled,
    slug = excluded.slug,
    config = excluded.config,
    cron_effective = excluded.cron_effective,
    last_at = excluded.last_at,
    hits = excluded.hits,
    updated_at = excluded.updated_at
`

type UpsertTriggerParams struct {
	ID            string
	Kind          string
	FlowID        string
	StartNodeID   string
	Title         string
	Enabled       int64
	Slug          string
	Config        string
	CronEffective string
	LastAt        int64
	Hits          string
	CreatedAt     int64
	UpdatedAt     int64
}

func (q *Queries) UpsertTrigger(ctx context.Context, arg UpsertTriggerParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrigger,
		arg.ID,
		arg.Kind,
		arg.FlowID,
		arg.StartNodeID,
		arg.Title,
		arg.Enabled,
		arg.Slug,
		arg.Config,
		arg.CronEffective,
		arg.LastAt,
		arg.Hits,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
