// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflows.sql

package sqlcgen

import (
	"context"
)

const countWorkflows = `-- name: CountWorkflows :one
SELECT COUNT(*) FROM workflows
WHERE (?1 = '' OR title LIKE '%' || ?1 || '%')
`

func (q *Queries) CountWorkflows(ctx context.Context, search interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkflows, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :execrows
DELETE FROM workflows WHERE id = ?1
`

func (q *Queries) DeleteWorkflow(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWorkflow, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, title, view_flow, created_at, updated_at FROM workflows WHERE id = ?1
`

func (q *Queries) GetWorkflow(ctx context.Context, id string) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflow, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ViewFlow,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, title, view_flow, created_at, updated_at FROM workflows
WHERE (?1 = '' OR title LIKE '%' || ?1 || '%')
ORDER BY updated_at DESC, id DESC
LIMIT ?3 OFFSET ?2
`

type ListWorkflowsParams struct {
	Search interface{}
	Offset int64
	Limit  int64
}

func (q *Queries) ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflows, arg.Search, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ViewFlow,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkflow = `-- name: UpsertWorkflow :exec
INSERT INTO workflows (id, title, view_flow, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(id) DO UPDATE SET
    title = excluded.title,
    view_flow = excluded.view_flow,
    updated_at = excluded.updated_at
`

type UpsertWorkflowParams struct {
	ID        string
	Title     string
	ViewFlow  string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) UpsertWorkflow(ctx context.Context, arg UpsertWorkflowParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkflow,
		arg.ID,
		arg.Title,
		arg.ViewFlow,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
